import type { CatalogSeries } from "@/lib/catalog/catalog";

export const catalogSeriesFixture = (
    key: string,
    overrides: Partial<CatalogSeries> = {},
): CatalogSeries => ({
    id: 1_000_001,
    key,
    title: key,
    updatedAt: 1_700_000_000,
    groupId: null,
    baseTitle: null,
    seasonNumber: null,
    coverImage: "/poster.jpg",
    posterImage: "/poster.jpg",
    backdropImage: null,
    backdropSource: null,
    logoImage: null,
    synopsis: null,
    rating: "Local",
    ageRating: null,
    year: null,
    focalX: null,
    focalY: null,
    safeLeft: null,
    safeBottom: null,
    dominantColor: null,
    placeholder: null,
    posterDominantColor: null,
    posterPlaceholder: null,
    backdropDominantColor: null,
    backdropPlaceholder: null,
    studio: null,
    audioLanguages: [],
    subtitleLanguages: [],
    metadataProvider: null,
    externalId: null,
    tmdbExternalId: null,
    genres: [],
    altTitles: [],
    hasMetadata: true,
    visibility: "public",
    episodeCount: 1,
    episodes: [{
        key: "01.mp4",
        number: 1,
        sizeBytes: 1024,
        addedAt: 1_700_000_000,
        title: null,
        synopsis: null,
        durationSeconds: 1200,
        thumbnail: null,
        media: null,
        url: null,
    }],
    bannerImage: null,
    sourceCoverImage: "/poster.jpg",
    sourceRating: null,
    access: "full",
    ...overrides,
});
